//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Desktop.UI.Database.Entity_Data_Model.Admin_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPATION
    {
        public string EMP_EMAIL { get; set; }
        public short PROJECT_ID { get; set; }
        public string ROLE { get; set; }
        public Nullable<short> HOURS { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
