//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Desktop.UI.Database.Entity_Data_Model.Admin_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKS
    {
        public int TASK_ID { get; set; }
        public string TASK_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public short DURATION { get; set; }
        public short PROJECT_ID { get; set; }
    
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
