drop procedure INSERT_INTO_EMPLOYEES;
drop procedure DELETE_FROM_EMPLOYEES;
drop procedure UPDATE_EMPLOYEES;
drop procedure INSERT_INTO_JOBS;
drop procedure DELETE_FROM_JOBS;
drop procedure UPDATE_JOBS;
drop procedure INSERT_INTO_DEPARTMENTS;
drop procedure DELETE_FROM_DEPARTMENTS;
drop procedure UPDATE_DEPARTMENTS;
drop procedure INSERT_INTO_LOCATIONS;
drop procedure DELETE_FROM_LOCATIONS;
drop procedure UPDATE_LOCATIONS;
drop procedure INSERT_INTO_COUNTRIES;
drop procedure DELETE_FROM_COUNTRIES;
drop procedure UPDATE_COUNTRIES;
drop procedure INSERT_INTO_PROJECTS;
drop procedure DELETE_FROM_PROJECTS;
drop procedure UPDATE_PROJECTS;
drop procedure INSERT_INTO_TASKS;
drop procedure DELETE_FROM_TASKS;
drop procedure UPDATE_TASKS;
drop procedure INSERT_INTO_PARTICIPATION;
drop procedure DELETE_FROM_PARTICIPATION;
drop procedure UPDATE_PARTICIPATION;
drop procedure HIRE_EMPLOYEE;
drop procedure FIRE_EMPLOYEE;
drop procedure PROMOTE_EMPLOYEE;
drop procedure INSERT_INTO_VACATIONS;
drop procedure DELETE_FROM_VACATIONS;
drop procedure UPDATE_VACATIONS;
drop procedure EXPORT_JSON;
drop function ENCRYPT;
drop function LOGIN_EMPLOYEE;
drop function DECRYPT;
drop procedure IMPORT_JSON;

DROP INDEX idx_vacations_emp_id;
DROP INDEX idx_countries_country_id;
DROP INDEX idx_departments_department_id;
DROP INDEX idx_locations_location_id;
DROP INDEX idx_participation_emp_project;
DROP INDEX idx_projects_project_id;
DROP INDEX idx_tasks_task_id;
DROP INDEX idx_jobs_job_id;

DROP TABLE participation cascade constraints;
DROP TABLE tasks cascade constraints;
DROP TABLE projects cascade constraints;
DROP TABLE vacations cascade constraints;
DROP TABLE employees cascade constraints;
DROP TABLE departments cascade constraints;
DROP TABLE jobs cascade constraints;
DROP TABLE locations cascade constraints;
DROP TABLE countries cascade constraints;

DROP SEQUENCE participation_id_seq;
DROP SEQUENCE countries_id_seq;
DROP SEQUENCE job_id_seq;
DROP SEQUENCE department_id_seq;
DROP SEQUENCE location_id_seq;
DROP SEQUENCE project_id_seq;
DROP SEQUENCE task_id_seq;
DROP SEQUENCE emp_id_seq;
DROP SEQUENCE vacation_id_seq;

DROP TRIGGER vacation_id_trg;
DROP TRIGGER task_id_trg;
DROP TRIGGER project_id_trg;
DROP TRIGGER country_id_trg;
DROP TRIGGER location_id_trg;
DROP TRIGGER department_id_trg;
DROP TRIGGER job_id_trg;
DROP TRIGGER emp_id_trg;