begin INSERT_INTO_JOBS('test', 'test_OLD', 20000, 40000); end;
SELECT * FROM JOBS WHERE job_id = 'test';

begin UPDATE_JOBS('test', 'test_NEW', 20000, 50000); end;
SELECT * FROM JOBS WHERE job_id = 'test';

begin DELETE_FROM_JOBS('test'); end;
SELECT * FROM JOBS WHERE job_id = 'test';





begin INSERT_INTO_COUNTRIES ('TE', 'TEST_OLD'); end;
SELECT * FROM COUNTRIES WHERE country_id = 'TE';

begin UPDATE_COUNTRIES ('TE', 'TEST_NEW'); end;
SELECT * FROM COUNTRIES WHERE country_id = 'TE';

begin DELETE_FROM_COUNTRIES('TE'); END;
SELECT * FROM COUNTRIES WHERE country_id = 'TE';





begin INSERT_INTO_LOCATIONS('TEST_OLD', '12345', 'TEST', 'NY', 'US'); end;
SELECT * FROM LOCATIONS WHERE CITY = 'TEST';

begin UPDATE_LOCATIONS(11, 'TEST_NEW', '12345', 'TEST', 'NY', 'US'); end;
SELECT * FROM LOCATIONS WHERE CITY = 'TEST';

begin DELETE_FROM_LOCATIONS(11); end;
SELECT * FROM LOCATIONS WHERE CITY = 'TEST';





begin INSERT_INTO_DEPARTMENTS('TEST_OLD', 1, 1); end;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'TEST_OLD';

begin UPDATE_DEPARTMENTS(11,'TEST_NEW',1, 1); end;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'TEST_NEW';

begin DELETE_FROM_DEPARTMENTS(11); end;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'TEST_NEW';





begin INSERT_INTO_PROJECTS ('TEST_OLD', TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2022-06-30', 'YYYY-MM-DD'), 50000.00, 1); end;
SELECT * FROM PROJECTS WHERE PROJECT_NAME = 'TEST_OLD';

begin UPDATE_PROJECTS(11,'TEST_NEW', TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2022-06-30', 'YYYY-MM-DD'), 50000.00, 1); end;
SELECT * FROM PROJECTS WHERE PROJECT_NAME = 'TEST_NEW';

begin DELETE_FROM_PROJECTS(11); end;
SELECT * FROM PROJECTS WHERE PROJECT_NAME = 'TEST_NEW';





begin INSERT_INTO_TASKS ('TEST', 'OLD', 40, 1); end;
SELECT * FROM TASKS WHERE TASK_NAME ='TEST';

begin UPDATE_TASKS(11,'TEST', 'NEW', 40, 1); end;
SELECT * FROM TASKS WHERE TASK_NAME ='TEST';

begin DELETE_FROM_TASKS(11); end;
SELECT * FROM TASKS WHERE TASK_NAME ='TEST';





begin INSERT_INTO_EMPLOYEES('TEST_TEST', 'OLD', 'TEST_INSERT', '1234567890','AD_PRES', 50000, 0.1, NULL, 1, 'password1137'); end;
begin HIRE_EMPLOYEE('TEST_TEST', 'OLD', 'TEST_HIRE', '1234567890','AD_PRES', 50000, 0.1, NULL, 1, 'password1137'); end;
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'TEST_TEST';

begin UPDATE_EMPLOYEES(7,'TEST_TEST', 'NEW', 'TEST_INSERT', '1234567890','AD_PRES', 50000, 0.1, NULL, 1); end;
begin UPDATE_EMPLOYEES(8,'TEST_TEST', 'NEW', 'TEST_HIRE',   '1234567890','AD_PRES', 50000, 0.1, NULL, 1); end;
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'TEST_TEST';

begin DELETE_FROM_EMPLOYEES(10); END;
begin FIRE_EMPLOYEE(9); END;
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'TEST_TEST';





Begin INSERT_INTO_PARTICIPATION('test@example.com', 2, 'OLD', 40); end;
SELECT * FROM PARTICIPATION WHERE PROJECT_ID = 2 AND EMP_EMAIL = 'test@example.com';

Begin UPDATE_PARTICIPATION('test@example.com', 2, 'NEW', 40); end;
SELECT * FROM PARTICIPATION WHERE PROJECT_ID = 2 AND EMP_EMAIL = 'test@example.com';

begin delete_from_participation('test@example.com', 2); end;
SELECT * FROM PARTICIPATION WHERE PROJECT_ID = 2 AND EMP_EMAIL = 'test@example.com';





begin INSERT_INTO_VACATIONS('test@example.com', TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2022-07-15', 'YYYY-MM-DD'), 'OLD'); end;
SELECT * FROM VACATIONS WHERE EMP_EMAIL = 'test@example.com';

begin Update_vacations(11,'test@example.com', TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2022-07-15', 'YYYY-MM-DD'), 'NEW'); end;
SELECT * FROM VACATIONS WHERE EMP_EMAIL = 'test@example.com';

begin delete_from_vacations(11); end;
SELECT * FROM VACATIONS WHERE EMP_EMAIL = 'test@example.com';